pragma foreign_keys = 'ON';
insert into registration (name, email_id, password) values('Kaustav Chakraborty', 'kaustav.ron@gmail.com', '12345');
insert into registration (name, email_id, password) values('Prasenjit Chakraborty', 'prasenjitc@gmail.com', '54321');
insert into topics (name, description, userId, start_time, end_time) values('step','software technology excelence program',1,'GMT 15:00','GMT 21:9809');
insert into topics (name, description, userId, start_time) values('step of success','nobel thought',2,'GMT 5:30');
insert into topics (name, description, userId, start_time) values('soda','how to make drink',1,'GMT 6:76');
insert into topics (name, description, userId, start_time) values('hocky','hocky is our national game',1,'GMT 15:30');
insert into joinedTopics (userId, topic_id) values (1,2);
insert into joinedTopics (userId, topic_id) values (2,1);
insert into joinedTopics (userId, topic_id) values (2,3);
insert into joinedTopics (userId, topic_id) values (1,3);